### ISSUE TITLE
i can't install it 

### ISSUE THREAD

**Issue by zlbben** [Jianru-Lin/lambda-view#31]
this is my log : 
/usr/local/bin/lv -> /usr/local/lib/node_modules/lambda-view/lv.js
/usr/local/bin/lv-svr -> /usr/local/lib/node_modules/lambda-view/lv-svr.js

> lambda-view@5.6.3 postinstall /usr/local/lib/node_modules/lambda-view
> node lv-svr.js stop

stopping lambda-view web server...
module.js:457
    throw err;
    ^

Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/lambda-view/node_modules/fmtjs-web/api/start.js:1:89)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/lib/node_modules/tnpm/node_modules/npm/bin/npm-cli.js" "install" "--cache=/Users/melonzhang/.tnpm" "--node_sqlite3_binary_host_mirror=https://tnpm-hz.oss-cn-hangzhou.aliyuncs.com/dist/" "--fse_binary_host_mirror=https://tnpm-hz.oss-cn-hangzhou.aliyuncs.com/dist/fsevents/" "--no-proxy" "--disturl=https://tnpm-hz.oss-cn-hangzhou.aliyuncs.com/dist/node" "--userconfig=/Users/melonzhang/.tnpmrc" "--registry=http://registry.npm.alibaba-inc.com" "lambda-view" "-g"
npm ERR! node v6.6.0
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! lambda-view@5.6.3 postinstall: `node lv-svr.js stop`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lambda-view@5.6.3 postinstall script 'node lv-svr.js stop'.
npm ERR! This is most likely a problem with the lambda-view package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lv-svr.js stop
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lambda-view
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls lambda-view
npm ERR! There is likely additional logging output above.

> lambda-view@5.6.3 preuninstall /usr/local/lib/node_modules/lambda-view
> node lv-svr.js stop

stopping lambda-view web server...
module.js:457
    throw err;
    ^

Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/lambda-view/node_modules/fmtjs-web/api/start.js:1:89)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
npm WARN continuing anyway lambda-view@5.6.3 preuninstall: `node lv-svr.js stop`
npm WARN continuing anyway Exit status 1

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/melonzhang/Desktop/graphQL/vue-apollo/npm-debug.log

**Comment by zlbben** [comment]
when i upgrade my node version to 6.10.2 , it success

**Comment by Jianru-Lin** [comment]
@zlbben Thanks for your report. The reason is **I forgot to add ```debug``` to dependency list of ```fmtjs-web```**. I have fixed this problem, you can try to reinstall lambda-view again. By the way, I found another problem: **My npm version is different (v4.4.4) from yours (2.15.11).** Maybe update your npm is needed too:

```
sudo npm install -g npm
```

Thansk.
